import type { Job } from './types';

export const placeholderJobs: Job[] = [
  {
    id: '1',
    title: 'Frontend Developer',
    company: 'Innovate Inc.',
    companyUrl: 'https://innovate-inc.com',
    location: 'Bengaluru, India',
    description: 'We are looking for a skilled Frontend Developer to join our team...',
    url: '#',
  },
  {
    id: '2',
    title: 'UI/UX Designer',
    company: 'Creative Solutions',
    companyUrl: 'https://creative-solutions.com',
    location: 'Mumbai, India',
    description: 'Join our design team to create beautiful and intuitive user experiences.',
    url: '#',
  },
  {
    id: '3',
    title: 'Data Analyst',
    company: 'Numbers Co.',
    companyUrl: 'https://numbers-co.com',
    location: 'Pune, India',
    description: 'Analyze large datasets to provide actionable insights for our business.',
    url: '#',
  },
  {
    id: '4',
    title: 'Project Manager',
    company: 'Lead Ventures',
    companyUrl: 'https://lead-ventures.com',
    location: 'Hyderabad, India',
    description: 'Manage complex projects from start to finish in a fast-paced environment.',
    url: '#',
  },
    {
    id: '5',
    title: 'Software Engineer, Backend',
    company: 'TechCore',
    companyUrl: 'https://techcore-inc.com',
    location: 'Gurugram, India',
    description: 'Develop and maintain server-side logic, databases, and APIs.',
    url: '#',
  },
  {
    id: '6',
    title: 'Product Marketing Manager',
    company: 'MarketLeap',
    companyUrl: 'https://marketleap.com',
    location: 'Noida, India',
    description: 'Drive the marketing strategy for our new line of software products.',
    url: '#',
  },
];
